language: php
php:
- 5.4
- 5.5
- 5.6
- 7.0
before_script:
- sudo apt-get update -qq
- sudo apt-get install -y --force-yes apache2 libapache2-mod-php5 php5-curl php5-mysql
  php5-intl php5-gd mutt > /dev/null
- sudo /etc/init.d/apache2 stop
- sudo sed -i -e "s,APACHE_RUN_USER=www-data,APACHE_RUN_USER=$USER,g" /etc/apache2/envvars
- sudo sed -i -e "s,APACHE_RUN_GROUP=www-data,APACHE_RUN_GROUP=$USER,g" /etc/apache2/envvars
- sudo chown -R $USER /var/lock/apache2
- sudo chown -R $USER:$USER /var/www
- ln -s $TRAVIS_BUILD_DIR/tests/ /var/www/tests
- sudo sed -i -e "s,AllowOverride[ ]None,AllowOverride All,g" /etc/apache2/sites-available/default
- ls /etc/apache2/sites-enabled
- sudo /etc/init.d/apache2 start
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
- sudo apt-get install fluxbox -y --force-yes
- fluxbox &
- sleep 3
- composer self-update
- composer update
script:
- mv tests/acceptance.suite.dist.yml tests/acceptance.suite.yml
- pwd
- php vendor/bin/robo test:acceptance
after_failure:
- php vendor/bin/robo send:email $CLOUD_NAME $API_KEY $API_SECRET
- cat /var/log/apache/error.log
env:
  global:
  - secure: r7pXGMRBytpP4oGxGmzzsu2J+eELL2168164uIq3/XOvok/pAmjg6UQLR1jtpgHTGgw3TNNpVRMGSCMqP9Gi7nPm/0SLIkgj27HvPW8RhCSykPoYYIbxRn9ytb6DC94fOTwH6oHn4jLI2WCJ3zIZIwyJZ373Eq9aValgfyE9ZrAn50pzxlWERA74ivNLFSIuBX+nDive0F2aCQ+n5ABbX2AGwvYCzX0vvq+N/TzCOFNCtbw9NdTfeQMlBCxYG9T0/HKNg6ROq/lmBeBPsbS/al7sJiGG37rO/Z+E6wFcsor3v/uBMbgIOb4Z6qbfJd4hAJHOpLsC7IgvqW/hD5w1KwSGrhbP/sKAwhLcs5lqQVDKNnwcT4Ja/dcl2Dt1G7b8kBmU9K9EaxNvxhQtf1N58QVcUbvSetbu56E4GpW0XlqPgg1cq5HUgfo6/mbfGW22v6nDtwsjgVfGxfS1QpJmJc34wmK7a9JTAWSNf7OsnoAEJcOuH7pm30gynY377D9aIR4cRxRl2Lxo2bfh9ltsc6iaMy1YrZhcrQIx8K0Se5LfVPuD55fnNgZ7eFnRCb1lNbbI74pZeTeXW6Cqk48NiaF26f+8+g4AxZ4V5BHUalyc/qEurKBR2w6HzWy4oUVztja6r+NyR0kZ+CsVRRaTa358zuuRwTMKexFPYgs16NM=
  - secure: ai/l/Pfc+p35hTcR22b+yx4ZCLdsv6b20xR6R+BGmuvrj56eT8LFcnXBoYjMtG15sqFcNabGjdJ1gKVZEydnjSSa6qTuo/UI1tbfmNU4aDM5VLT+Tmy8SIXLHFRlIwlQZkGkCb0fIfnLmG3DH2NHFyrcNciFI66JXXtAbCikPBcclskQB5cLdRC8txTFPHq8Fee4VuJ1hWxmKQuEbV2DO3OiYfGu03JaEArFybQrAvpGEmcEQv+/yAENYJJ1CoD1Za2ImvwoFMaZQegiEwSTXMQw573IHr6R5yr+MfQxZX7i3jdN6MLNDb8beKeThCcY0TnKUGE+2mPPclJGFFFxc57EP/MzWeYTv7Dta6FoG8g3wpabz+oR0/+0tFSxDORMKpBhkVEItU4yZ5HTLsBeaGo2jxsYMgJ4X7spyOBTk/kqSvTC+xlDFInjE3s2Payx09e9netBsI4NoJSe+Ba6erZ2gybzmMgyGqohwEmGz7lc/i69cB+vvhzbycMe4aHHwIjSRdtdrTBtczlmD52sDMf0+7/jbygRy0xQcZ9YwugWcu4FC7A9kbEpPA+qEVHlOw3iBvAxf52KhXDXyU/UhydyfZ3Kz6YlzFZ4tzMvPzMLYr1HRyDP5LcJhtyAsgszMCcVVF0sHbBJiu0BvXUESa4wM1iMH3rjK9B0JBiQyTU=
  - secure: juLwnolm5F01nNWmvtc25j2LkddrE90PVEJCtGLFOaUl0zRoAfBJhUwltWZHh4bMru+RwLR+uPgPBzFfIHA0cP9Go2sfgPcvgoimnf1+UcBhF1DoSleKVc2RV7QLr9krf/v1DFzv/DTpPvQau4fftmbAZC9Vr4ad0AICIBYNDaNGfZOvugV6vYiHYwxhj2lp9rdbpZJOUuUDv8f+CsLjbncOpp362YtqcuQMVq4OzzDMLW88o9vP7M7z3uy8RnFlzPJ7YtJ23uUNvvSOt2OqWv1crdpba4MUuFJiFH/WQWdwXBTmSsKmfnnePGS+mdaA78AkW9ne9tpYUKDDCNWO7thmc//rpLKaRSCGf7GHWZe/oczkSgPmPapTMUgMq+QQ720UHOsyZ7J6krxNICQFBt1M4U3WZe8iRKU8rvbvF5xxlslTTsgjbD8ONPRx1l06FOiTXs0kOxpA393fTEFI9bHnTTXf8BHXF3ZC1xQi9Et3ugfvYptfjRrEnWvXq7gdInR5nPx9HHsPsfWfJBUzr2cMviFZMWk236hLG1jHYrL4VETn8AUzjM7DxB415z6rC5bLM4X7DSNcGNnpJz/ippgIlIPX4T3fBb6Amv/SBo9ncsu2n5FES8hB/HqQgk7RgUykuHBH4W5gmZx95oJNF+np9s8WUlsAv16Yd/Ho1Nc=
